# Generated by Django 4.0.4 on 2024-03-19 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfomance',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.play'),
        ),
        migrations.AddField(
            model_name='perfomance',
            name='theatre_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.theatrehall'),
        ),
    ]
