# Generated by Django 4.0.4 on 2024-03-26 21:04

from django.db import migrations, models
import theatre.models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0002_alter_performance_theatre_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='image',
            field=models.ImageField(null=True, upload_to=theatre.models.play_image_file_path),
        ),
    ]
